[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"

[server]
maxUploadSize = 200
enableXsrfProtection = false

[browser]
gatherUsageStats = false